"""change availability status to string

Revision ID: d279a4e0c567
Revises: 40ecc8b039b4
Create Date: 2026-07-03 09:00:48.101784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd279a4e0c567'
down_revision: Union[str, Sequence[str], None] = '40ecc8b039b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'availabilityStatus',
               existing_type=postgresql.ENUM('ON_DUTY', 'OFF_DUTY', 'ON_LEAVE', name='availability_status'),
               type_=sa.String(),
               existing_nullable=False,
               schema='doctor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'availabilityStatus',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ON_DUTY', 'OFF_DUTY', 'ON_LEAVE', name='availability_status'),
               existing_nullable=False,
               schema='doctor')
    # ### end Alembic commands ###
