"""create appointments table

Revision ID: e3ccfd368474
Revises: 
Create Date: 2026-07-06 18:48:48.211955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ccfd368474'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patientId', sa.String(), nullable=False),
    sa.Column('doctorId', sa.String(), nullable=False),
    sa.Column('hospitalId', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('urgency', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scheduledAt', sa.DateTime(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='appointment'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments', schema='appointment')
    # ### end Alembic commands ###
