"""add address to patients

Revision ID: 5e9e2c6293c5
Revises: 99ab786611d8
Create Date: 2026-07-01 08:07:14.921800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e9e2c6293c5'
down_revision: Union[str, Sequence[str], None] = '99ab786611d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('patients', sa.Column(
        'address', sa.String(), nullable=False), schema='patient')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'address', schema='patient')
    op.create_table('alembic_version',
                    sa.Column('version_num', sa.VARCHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint(
                        'version_num', name=op.f('alembic_version_pkc'))
                    )
    op.create_table('patients',
                    sa.Column('id', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('age', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('gender', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('contact', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('hospitalId', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('patients_pkey'))
                    )
    # ### end Alembic commands ###
