"""create patients table

Revision ID: 99ab786611d8
Revises: 
Create Date: 2026-06-30 09:46:10.197553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ab786611d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=False),
                    sa.Column('gender', sa.String(), nullable=False),
                    sa.Column('contact', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('hospitalId', sa.String(), nullable=False),
                    sa.Column('createdAt', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='patient'
                    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_table('patients', schema='patient')
    # ### end Alembic commands ###
